### ISSUE TITLE
Error saving data to Chroma: no such table: collections

### ISSUE THREAD

**Issue by dinhvanlinh0610** [bangoc123/drop-rag#1]
I followed the instructions in README.md.
After I uploaded the csv file and pressed "Save Data", the error appeared.
Error saving data to Chroma: no such table collections.
I did not find any mention of table collections in the code.
![6064332649465494851](https://github.com/user-attachments/assets/5943a995-eebd-44d9-b5fa-5fa782626e83)

**Comment by bangoc123** [comment]
Let me check and get back to you!

**Comment by sonhmivirse** [comment]
I not found why the chromadb.Client not work in this app situation yet but you can fix current problem by go to the app.py file. In line 17. just replace it to be:
```python
st.session_state.client = chromadb.PersistentClient("db")
```

**Comment by bangoc123** [comment]
Nice. thank for your support @sonhmivirse

**Comment by dinhvanlinh0610** [comment]
great! It work for me. Thanks for your support @sonhmivirse

**Comment by chnrv9** [comment]
Actually, I am also getting the same error but it got fixed after I used PersistentClient. But it's not at all related to streamlit. I am guessing its more of memory handling error found in SQLite. I can't share the code because it's private, but yeah i am guessing it's still not fixed yet.
