### ISSUE TITLE
How to use Ollama from order Server.

### ISSUE THREAD

**Issue by dongsuperbo007** [bangoc123/drop-rag#13]
I Run Ollama run from orther server in LAN (example: 192.168.1.10:11434) becauses i run app in my PC (Ip: 192.168.1.7). thank you. My PC is lap top also i cant run Ollama.

**Comment by bangoc123** [comment]
Add and .env file and set `OLLAMA_ENDPOINT=192.168.1.10:11434`, it will use the IP
