### ISSUE TITLE
Looks like I'm having a little problem with chromaDB

### ISSUE THREAD

**Issue by dongsuperbo007** [bangoc123/drop-rag#16]
i run on win11

i have 3 docx files

gs01.docx - 15.9KB
gs02.docx - 14.9KB
gs03.docx - 17.4KB

after updating I see the data table has 105 rows (add row 0 to make it 106)

However when I choose save data

![image](https://github.com/user-attachments/assets/e61ed2a6-d004-454b-a61d-27b72d4a9220)

and my powershell

![image](https://github.com/user-attachments/assets/f15b748c-ee61-409c-a756-43697354fb28)

The program automatically exited.

I think maybe I have a C++ problem or some DB problem.

I am using C++ 2015-2022 version 14.40.33816.0

I have tried using 1 or 2 files out of the 3 docx files above. the system still works fine. however when using 3 files at the same time there is a problem.

Note: I tested on another PC. running win 10 server. using C++ the following versions:

![image](https://github.com/user-attachments/assets/6b41f2a6-188b-4e0b-95da-50722353dd0b)

works fine when i use 3 files at the same time and no errors.

Thank you for support

**Comment by bangoc123** [comment]
Please send us the file if possible. Our email is protonxai@gmail.com. We will test it and send you a response.

**Comment by bangoc123** [comment]
We tested it, and it works fine; we were unable to reproduce the bug.

Some recommendations for you: please install the tools by running:

```bash
pip install _distutils_hack
```
