### ISSUE TITLE
The program is stopped while executing

### ISSUE THREAD

**Issue by dinhvanlinh0610** [bangoc123/drop-rag#5]
![image](https://github.com/user-attachments/assets/bfb4d865-66b5-4de5-a919-a1cacf262327)
![image](https://github.com/user-attachments/assets/a8b91eb7-1958-459d-b7cc-dac7419ec06f)

After semantic chunking was successful, I pressed save data and after a period of running, the program automatically stopped without any error messages. I also monitored my computer's RAM but it was only at 70% and there was no memory overflow. 
The pdf file I used is only 607kb with 35 pages. Can anyone tell me what the problem I'm having is? Is there any way to solve it?

**Comment by bangoc123** [comment]
Can you provide the pdfs?

**Comment by thuyduong19062004** [comment]
@bangoc123 
[VanBanGoc_52.2014.QH13.pdf](https://github.com/user-attachments/files/17374099/VanBanGoc_52.2014.QH13.pdf)

**Comment by dinhvanlinh0610** [comment]
[VanBanGoc_52.2014.QH13.pdf](https://github.com/user-attachments/files/17374118/VanBanGoc_52.2014.QH13.pdf)
@bangoc123 
Here is the pdf file I was talking about.

**Comment by bangoc123** [comment]
It's still working on my local environment.

![Screen Shot 2024-10-15 at 14 58 22](https://github.com/user-attachments/assets/c651a221-86d8-4631-a880-d253976eca85). 

Please pull the latest code to ensure nothing is broken.

**Comment by dinhvanlinh0610** [comment]
@bangoc123  Thank you very much for your help. 
Maybe the problem comes from my computer. I tried running the project on another PC and it worked fine. I'm not sure where the problem is. It could be due to RAM, or the version of the libraries or the version of python that is different
