### ISSUE TITLE
Lỗi khi semanticChunker file docx

### ISSUE THREAD

**Issue by thuyduong19062004** [bangoc123/drop-rag#7]
[1. QĐ-1226-Quy che dao tao dai hoc-DHTL (ban hanh).docx](https://github.com/user-attachments/files/17377000/1.QD-1226-Quy.che.dao.tao.dai.hoc-DHTL.ban.hanh.docx)
Em chọn semantic chunker với file docx trên thì bị lỗi như sau: 
ValueError: empty vocabulary; perhaps the documents only contain stop words
![image](https://github.com/user-attachments/assets/0600f1cd-2b44-4dad-89fc-def7999ecf51)

**Comment by bangoc123** [comment]
Team sẽ kiểm tra và nhắn em mai nhé!

**Comment by bangoc123** [comment]
Team đã fix nhé em!
![Screen Shot 2024-10-16 at 09 54 22](https://github.com/user-attachments/assets/ba273eb7-60ea-47c3-9783-9df2f5c4c2f0)

**Comment by thuyduong19062004** [comment]
Em cảm ơn team ạ !
