### ISSUE TITLE
How use Lm Studio without Ollama

### ISSUE THREAD

**Issue by dongsuperbo007** [bangoc123/drop-rag#9]
i want to use Lm Studio instead of Ollama. can you guide me to edit your code?
because Lm Studio's GGUF is more diverse and flexible than Ollama

**Comment by bangoc123** [comment]
Hi, Ollama now supports GGUF, so you can use it via the UI here.
![gguf](https://github.com/user-attachments/assets/6cfb5011-a950-4f39-be0c-a937c4dd56d8)

**Comment by dongsuperbo007** [comment]
VeryGood. Tks admin
